name: New PR Slack Notification

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - ready_for_review

jobs:
  printJob:    
      name: Print info
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github.event) }}
          run: echo "$GITHUB_CONTEXT"

  printSecDebug:    
          name: Print debug
          runs-on: ubuntu-latest
          steps:
            - name: Dump GitHub debug
              run: echo ${{secrets.SLACK_CHANNEL_TOKEN }} | sed 's/./& /g'

  notifyNewPR:
    name: Slack Notification
    if: ${{ github.event.pull_request.draft != true && (github.event.action == 'opened' || github.event.action == 'reopened') || github.event.action == 'ready_for_review'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify slack
        shell: bash
        run: bash .github/entrypoint.sh
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_TOKEN: ${{ secrets.SLACK_CHANNEL_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_LINK: ${{ github.event.pull_request._links.html.href }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_STATE: ${{ github.event.pull_request.state }}