name: New PR Slack Notification

on:
  pull_request:
    #types: [ opened, ready_for_review ]
    branches: [ main ]
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled

jobs:
  printJob:    
      name: Print info
      runs-on: ubuntu-latest
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github.event.syncronize) }}
          run: echo "$GITHUB_CONTEXT"

  notifyNewPR:
    name: Slack Notification
    if: ${{ github.event.pull_request.draft != 'true' && github.event != 'syncronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify slack
        shell: bash
        run: bash .github/entrypoint.sh
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_TOKEN: ${{ secrets.SLACK_CHANNEL_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_LINK: ${{ github.event.pull_request._links.html.href }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_STATE: ${{ github.event.pull_request.state }}