name: Review Requested Slack Notification

on:
  pull_request:
    types: [ assigned, unassigned ]
    branches: [ main ]

jobs:
  notifyReviewRequested:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Review requested
        shell: bash
        run: bash .github/review-entrypoint.sh
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_TOKEN: U03S6A4DDCH
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_LINK: ${{ github.event.pull_request._links.html.href }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          #PR_REVIEW_REQ_TARGET: ${{  }}