name: Slack Notifications

on:
  pull_request:
    branches: [ main ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Notify slack
        shell: bash
        run: bash .github/entrypoint.sh
        env:
          DATA: |
            {
              "channel": ${{ secrets.SLACK_CHANNEL_TOKEN }}",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: *NEW PULL REQUEST*\n published by *${{ github.event.pull_request.user.login }}*\n\n <${{ github.event.pull_request._links.html.href }}|*${{ github.event.pull_request.title }}*>\n status: *${{ github.event.pull_request.state }}*"
                }
              },
               {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.event.pull_request._links.html.href }}|View Pull Request>"
                }
              }]
            }
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER_TOKEN: ${{ github.event.pull_request.user.login }}