name: Slack Notifications

on:
  pull_request:
    branches: [ main ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Notify slack
        shell: bash
        run: bash .github/entrypoint.sh
        env:
          DATA: |
            {
              "channel": "C03RD3YEJF9",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Pull Request:*\n ${{ github.event.pull_request.title }}"
                }
              }, {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Author:*\n${{ github.event.pull_request.user.login }}\n\n*State:*\n${{ github.event.pull_request.state }}"
                }
              }, {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.event.pull_request._links.html.href }}|View Pull Request>"
                }
              }]
            }
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}